DROP TABLE IF EXISTS terra_entities;

CREATE TYPE entity_type AS ENUM ('waypoint', 'route');

CREATE TABLE terra_entities (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT,
    user_id INTEGER NOT NULL REFERENCES terra_users(id),
    type entity_type NOT NULL,
    position FLOAT[][],
    date_created TIMESTAMP DEFAULT now() NOT NULL
)